// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igxuptposrsgirxgijbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlneHVwdHBvc3JzZ2lyeGdpamJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTcwNzQsImV4cCI6MjA2NDA3MzA3NH0.WUmZlAxlpv77gPmTleysJC0ynOHsLEtOsIZFDuqHhLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);